#ifndef CYGONCE_PKGCONF_SYSTEM_H
#define CYGONCE_PKGCONF_SYSTEM_H
/*
 * File <pkgconf/system.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_VERSION_CURRENT 0x7fffff00
#define CYGPKG_HAL v1_3_1
#define CYGPKG_HAL_v1_3_1
#define CYGNUM_HAL_VERSION_MAJOR 1
#define CYGNUM_HAL_VERSION_MINOR 3
#define CYGNUM_HAL_VERSION_RELEASE 1
#define CYGPKG_IO v1_3_1
#define CYGPKG_IO_v1_3_1
#define CYGNUM_IO_VERSION_MAJOR 1
#define CYGNUM_IO_VERSION_MINOR 3
#define CYGNUM_IO_VERSION_RELEASE 1
#define CYGPKG_INFRA v1_3_1
#define CYGPKG_INFRA_v1_3_1
#define CYGNUM_INFRA_VERSION_MAJOR 1
#define CYGNUM_INFRA_VERSION_MINOR 3
#define CYGNUM_INFRA_VERSION_RELEASE 1
#define CYGPKG_KERNEL v1_3_1
#define CYGPKG_KERNEL_v1_3_1
#define CYGNUM_KERNEL_VERSION_MAJOR 1
#define CYGNUM_KERNEL_VERSION_MINOR 3
#define CYGNUM_KERNEL_VERSION_RELEASE 1
#define CYGPKG_LIBC v1_3_1
#define CYGPKG_LIBC_v1_3_1
#define CYGNUM_LIBC_VERSION_MAJOR 1
#define CYGNUM_LIBC_VERSION_MINOR 3
#define CYGNUM_LIBC_VERSION_RELEASE 1
#define CYGPKG_LIBM v1_3_1
#define CYGPKG_LIBM_v1_3_1
#define CYGNUM_LIBM_VERSION_MAJOR 1
#define CYGNUM_LIBM_VERSION_MINOR 3
#define CYGNUM_LIBM_VERSION_RELEASE 1
#define CYGPKG_DEVICES_WALLCLOCK v1_3_1
#define CYGPKG_DEVICES_WALLCLOCK_v1_3_1
#define CYGNUM_DEVICES_WALLCLOCK_VERSION_MAJOR 1
#define CYGNUM_DEVICES_WALLCLOCK_VERSION_MINOR 3
#define CYGNUM_DEVICES_WALLCLOCK_VERSION_RELEASE 1
#define CYGPKG_ERROR v1_3_1
#define CYGPKG_ERROR_v1_3_1
#define CYGNUM_ERROR_VERSION_MAJOR 1
#define CYGNUM_ERROR_VERSION_MINOR 3
#define CYGNUM_ERROR_VERSION_RELEASE 1
#define CYGPKG_HAL_ARM v1_3_1
#define CYGPKG_HAL_ARM_v1_3_1
#define CYGNUM_HAL_ARM_VERSION_MAJOR 1
#define CYGNUM_HAL_ARM_VERSION_MINOR 3
#define CYGNUM_HAL_ARM_VERSION_RELEASE 1
#define CYGPKG_HAL_ARM_ZOT716U2 v1_3_1
#define CYGPKG_HAL_ARM_ZOT716U2_v1_3_1
#define CYGNUM_HAL_ARM_ZOT716U2_VERSION_MAJOR 1
#define CYGNUM_HAL_ARM_ZOT716U2_VERSION_MINOR 3
#define CYGNUM_HAL_ARM_ZOT716U2_VERSION_RELEASE 1
#define CYGBLD_HAL_TARGET_H   <pkgconf/hal_arm.h>
#define CYGBLD_HAL_PLATFORM_H <pkgconf/hal_arm_zot716u2.h>
#define CYG_HAL_STARTUP RAM
#define CYG_HAL_STARTUP_RAM
#define CYGHWR_MEMORY_LAYOUT_LDI <pkgconf/mlt_arm_zot716u2_ram.ldi>
#define CYGHWR_MEMORY_LAYOUT_H <pkgconf/mlt_arm_zot716u2_ram.h>
#define CYGPKG_IO_SERIAL v1_3_1
#define CYGPKG_IO_SERIAL_v1_3_1
#define CYGNUM_IO_SERIAL_VERSION_MAJOR 1
#define CYGNUM_IO_SERIAL_VERSION_MINOR 3
#define CYGNUM_IO_SERIAL_VERSION_RELEASE 1

#endif
