#ifndef CYGONCE_PKGCONF_LIBC_H
#define CYGONCE_PKGCONF_LIBC_H
/*
 * File <pkgconf/libc.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

/***** proc output start *****/
#include <pkgconf/system.h>
#define CYGPRI_LIBC_INLINE extern __inline__
#ifdef __GNUC__xxxxxx
# define CYGPRI_LIBC_ATTRIB_FORMAT_STRFTIME __attribute__ ((format (strftime, 3)))
#else
# define CYGPRI_LIBC_ATTRIB_FORMAT_STRFTIME
#endif
#define CYGPRI_LIBC_WEAK CYGBLD_ATTRIB_WEAK
#define CYGPRI_LIBC_ALIAS(__symbol__) __attribute__ ((alias (__symbol__)))
# define CYGPRI_LIBC_WEAK_ALIAS(__symbol__) CYGBLD_ATTRIB_WEAK CYGPRI_LIBC_ALIAS(__symbol__)
#define CYGPRI_LIBC_NORETURN CYGBLD_ATTRIB_NORET
/****** proc output end ******/
#define CYGPKG_LIBC_STRING 1
#define CYGIMP_LIBC_STRING_INLINES 1
#define CYGPKG_LIBC_STRING_STRTOK 1
#define CYGNUM_LIBC_STRTOK_TRACE_LEVEL 0
#define CYGNUM_LIBC_STRTOK_TRACE_LEVEL_0
#define CYGPKG_LIBC_STDLIB 1
#define CYGPKG_LIBC_RAND 1
#define CYGNUM_LIBC_RAND_SEED 1
#define CYGNUM_LIBC_RAND_SEED_1
#define CYGNUM_LIBC_RAND_TRACE_LEVEL 0
#define CYGNUM_LIBC_RAND_TRACE_LEVEL_0
#define CYGINT_LIBC_RAND 1
#define CYGINT_LIBC_RAND_1
#define CYGIMP_LIBC_RAND_SIMPLE1 1
#define CYGPKG_LIBC_MALLOC 1
#define CYGNUM_LIBC_MALLOC_MEMPOOL_SIZE 129024
#define CYGNUM_LIBC_MALLOC_MEMPOOL_SIZE_129024
#define CYGNUM_LIBC_BSEARCH_TRACE_LEVEL 0
#define CYGNUM_LIBC_BSEARCH_TRACE_LEVEL_0
#define CYGNUM_LIBC_QSORT_TRACE_LEVEL 0
#define CYGNUM_LIBC_QSORT_TRACE_LEVEL_0
#define CYGPKG_LIBC_STDIO 1
#define FOPEN_MAX 8
#define FOPEN_MAX_8
#define FILENAME_MAX 16
#define FILENAME_MAX_16
#define L_tmpnam 16
#define L_tmpnam_16
#define TMP_MAX 0
#define TMP_MAX_0
#define BUFSIZ 0
#define BUFSIZ_0
#define CYGDAT_LIBC_STDIO_DEFAULT_CONSOLE "/dev/ser0"
#define CYGPKG_LIBC_STDIO_FLOATING_POINT 1
#define CYGNUM_LIBC_MAX_LOCALE_NAME_SIZE 16
#define CYGNUM_LIBC_MAX_LOCALE_NAME_SIZE_16
#define CYGPKG_LIBC_STARTUP 1
#define CYGDAT_LIBC_ARGUMENTS {"", NULL}
#define CYGPKG_LIBC_ERRNO 1
#define CYGNUM_LIBC_ERRNO_TRACE_LEVEL 0
#define CYGNUM_LIBC_ERRNO_TRACE_LEVEL_0
#define CYGPKG_LIBC_TIME 1
#define CYGSEM_LIBC_TIME_TIME_WORKING 1
#define CYGPKG_LIBC_TIME_ZONES 1
#define CYGNUM_LIBC_TIME_DST_DEFAULT_STATE -1
#define CYGNUM_LIBC_TIME_STD_DEFAULT_OFFSET 0
#define CYGNUM_LIBC_TIME_STD_DEFAULT_OFFSET_0
#define CYGNUM_LIBC_TIME_DST_DEFAULT_OFFSET 3600
#define CYGNUM_LIBC_TIME_DST_DEFAULT_OFFSET_3600
#define CYGPKG_LIBC_TIME_INLINES 1
#define CYGNUM_LIBC_TIME_CLOCK_TRACE_LEVEL 0
#define CYGNUM_LIBC_TIME_CLOCK_TRACE_LEVEL_0
#define CYGPKG_LIBC_OPTIONS 1

#endif
